on:
  - pull_request

env:
    tf_actions_working_dir: .

jobs:
  terraform-verify:
    name: 'Terraform Verify'
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1.2.1
      with:
        terraform_wrapper: false

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Integration tests
      id: test
      run: make test
