on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    if: github.event.pull_request.merged == true
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
